## Min Max Scallilng 
* Rescale the value to the range of 0 , 1 
* All the features need to be scaled, especially for algorithm using distance metric

In [2]:
from sklearn.preprocessing import MinMaxScaler
import pandas as pd

In [5]:
data = {
    'Name': ["Abdullah","Omer","Talha","Ali"],
    "Age":[18,25,30,50]
}
df = pd.DataFrame(data)
df

       Name  Age
0  Abdullah   18
1      Omer   25
2     Talha   30
3       Ali   50

In [ ]:
scaler = MinMaxScaler()
df['Normalized Age'] = scaler.fit_transform(df[['Age']])
df

       Name  Age  Normalized Age
0  Abdullah   18         0.00000
1      Omer   25         0.21875
2     Talha   30         0.37500
3       Ali   50         1.00000