In [17]:
from sklearn.preprocessing import StandardScaler
import pandas as pd

In [18]:
data = {
    'Name': ["Abdullah", "Omer", "Talha", "Ali"],
    "Age": [18, 25, 30, 50]
}
df = pd.DataFrame(data)
df

       Name  Age
0  Abdullah   18
1      Omer   25
2     Talha   30
3       Ali   50

In [44]:
# Step 1: Get age list
ages = data['Age']

# Step 2: Calculate mean
mean_age = sum(ages) / len(ages)

# Step 3: Calculate standard deviation (sample or population – using population here)
squared_diffs = [(x - mean_age) ** 2 for x in ages]
std_age = (sum(squared_diffs) / len(ages)) ** 0.5

# Step 4: Apply scaling formula x_scaled = (x - mean) / std
scaled_ages = [(x - mean_age) / std_age for x in ages]

# Output
print(f"Mean: {mean_age}")
print(f"Standard Deviation: {std_age}")
print("Scaled Ages:")
for original, scaled in zip(ages, scaled_ages):
    print(f"Original: {original} → Scaled: {scaled}")

Mean: 30.75
Standard Deviation: 11.903255857117413
Scaled Ages:
Original: 18 → Scaled: -1.0711355072130357
Original: 25 → Scaled: -0.48306111109607497
Original: 30 → Scaled: -0.06300797101253151
Original: 50 → Scaled: 1.6172045893216422

In [45]:
import numpy as np

ages = np.array(data['Age'])
mean_age = np.mean(ages)
std_age = np.std(ages)

scaled_ages = (ages - mean_age) / std_age
print("Scaled ages:", scaled_ages)

Scaled ages: [-1.07113551 -0.48306111 -0.06300797  1.61720459]

In [43]:
scaler = StandardScaler()
df['Standard Scaled'] = scaler.fit_transform(df[['Age']])
df

       Name  Age  Standard Scaled
0  Abdullah   18        -1.071136
1      Omer   25        -0.483061
2     Talha   30        -0.063008
3       Ali   50         1.617205